### ISSUE TITLE
malformed PBS directive not checked with "nodes"

### ISSUE THREAD

**Issue by mselwa** [gjbex/qlint#17]
#PBS -l walltime=0:15:00
#PBS l nodes=1:ppn=20
leads to error
Traceback (most recent call last):
  File "/vsc-hard-mounts/leuven-apps/common/qlint/bin/../scripts/qlint.py", line 62, in <module>
    job_checker.check(pbs_parser.job)
  File "/vsc-hard-mounts/leuven-apps/common/vsc-tools-lib/lib/vsc/pbs/check.py", line 23, in check
    self.check_features(job)
  File "/vsc-hard-mounts/leuven-apps/common/vsc-tools-lib/lib/vsc/pbs/check.py", line 46, in check_features
    for feature in node_spec['features']:
KeyError: 'features'

**Comment by gjbex** [comment]
Thanks for pointing this out.  This issue has been fixed.  (In case you wonder: the fix is in vsc-tools-lib, not in qlint itself, hence no commits to this repository.)
